=== muntaswir72562/labsheetXML/labsheet/labsheet-1/module1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="ResoucePerson">
    <xs:choice>
      <xs:sequence>
        <xs:element type="xs:string" name="Name" />
        <xs:element type="xs:string" name="Surname" />
      </xs:sequence>
      <xs:element type="xs:string" name="fullName" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="nameType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="shortName" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="Modules">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Module">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="nameType" />
              <xs:element name="Level" type="xs:integer" />
              <xs:element name="ResourcePerson" type="ResoucePerson"></xs:element>
            </xs:sequence>
            <xs:attribute name="code" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/labsheetXML/labsheet/labsheet-1/module1.xml
<?xml version="1.0" encoding="utf-8"?>
<Modules> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="module1.xsd" > 
    <Module code="CSE2041">
        <Name shortName="Web 2">Web TechnologiesII</Name>
        <Level>2</Level>
        <ResourcePerson>
            <FullName>Shehzad Jaunbuccus</FullName>
        </ResourcePerson>
    </Module>
    <Module
        code="CSE1246">
        <Name shortName="ADSA">Applied Data Structures andAlgorithms</Name>
        <Level>1</Level>
        <ResourcePerson>
            <Name>Anwar</Name>
            <Surname>Chutoo</Surname>
        </ResourcePerson>
    </Module>
</Modules>
