=== muntaswir72562/labsheetXML/labsheet/labsheet-w2,3,4/hello.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="page">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="title" />
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="paragraph" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="content" />
                                        <xs:element type="xs:string" name="comment" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== muntaswir72562/labsheetXML/labsheet/labsheet-w3,4/hello.xml
<?xml version="1.0" encoding="utf-8"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="hello.xsd">

    <title>Hello</title>
    <body>
        <paragraph>
            <content>This is some content.</content>
            <comment>Written by ABC.</comment>
        </paragraph>
        <paragraph>
            <content>This is another paragraph.</content>
            <comment>Written by XYZ.</comment>
        </paragraph>
    </body>
</page>
